# Default values for icinga2-hipchat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: lead4good/icinga2-hipchat
  tag: latest
  pullPolicy: Always
service:
  name: icinga2
  type: LoadBalancer
  externalPort: 80
  internalPort: 80
resources:
  requests:
    cpu: 1m
    memory: 1Mi
ingress:
  enabled: true
  ssl: true
  domain: example.com
